name: Security Scanning

on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Run GitLeaks for secret scanning
      - name: Run GitLeaks scan
        uses: gitleaks/gitleaks-action@v2 # Official GitLeaks action

      # Run Trivy for vulnerability scanning
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master # Official Trivy action
        with:
          scan-type: "fs"
          ignore-unfixed: true
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
